[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "0byte-sdk"
version = "0.1.0"
description = "Python SDK for 0byte image generation and proof anchoring"
authors = [{name="Your Name", email="you@example.com"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"

[project.dependencies]
requests = "^2.28"
pydantic = "^1.10"